create table property
(
[T-CODE], int,
[FISCAL_YEAR], int,
[MAP], int,
[BLOCK], varchar(500),
[LOT], varchar(500),
[UNIT], varchar(500),
[PARCEL ID], varchar(500) primary key,
[PCC], varchar(500),
[PCC DESCRIPT], varchar(500),
[ACCOUNT], int,
[HOUSE NO], int,
[STREET], varchar(500),
[COMMITMENT OWNER], varchar(500),
[CURRENT OWNER], varchar(500),
[CURRENT CO-OWNER], varchar(500),
[OWNER ADD], varchar(500),
[OWNER CITY], varchar(500),
[OWNER STATE], varchar(500),
[OWNER ZIP], varchar(500),
[SALE PRICE], int,
[SALE DATE], Date & Time,
[BOOK PAGE], varchar(500),
[CERT NO], int,
[BOARDER FLAG], varchar(500),
[SALE VALID], varchar(500),
[WARD], int,
[PRECINCT], int,
[PARCEL VAL], int,
[LAND VAL], int,
[IMPROVE VAL], int,
[SQFT], int,
[NHBD], int,
[SITE INDEX], varchar(500),
[BDLD NO], int,
[OCCUP], int,
[STYLE DESCRIP], varchar(500),
[STORIES], int,
[WALL TYPE 1], varchar(500),
[WALL TYPE 2], varchar(500),
[HEAT TYPE], varchar(500),
[FUEL TYPE], varchar(500),
[AC TYPE], varchar(500),
[GROSS AREA], int,
[LIVING AREA], int,
[ROOMS], int,
[BEDROOM], int,
[BATH], int,
[BATH DESCRIP], varchar(500),
[KITCHEN DESCRIP], varchar(500),
[PERCENT GOOD], int,
[GRADE DESCRIP], varchar(500),
[YEAR], int,
[RESX FLAG], Checkbox,
[LOCAL HISTORICAL], Checkbox,
[NATIONAL HISTORICAL], Checkbox,
[ZONE], varchar(500),
[ZONE DESP], varchar(500),
[EXEMPT AMT], int,
[TAX VALUE], int,
[Item Type1], varchar(500),
[Path1], varchar(500),
[Item Type], varchar(500),
[Path], varchar(500),
[ROOF STRUCTURE DESCRIP], varchar(500),
[ROOF COVER DESCRIP], varchar(500),
[INT WALL 1 DESCRIP], varchar(500),
[INT WALL 2 DESCRIP], varchar(500),
[INT FLOOR 1 DESCRIP], varchar(500),
[INT FLOOR 2 DESCRIP], varchar(500),
[HAS GARAGE], varchar(500),
[Sub Lots], varchar(500),
[AV PID], varchar(500)
)
